Repository DataDog/agent-linux-install-script, pull requests merged in 2024-08, with the labels that each got.

#250 [Documentation] Fix link to in-app installation page
  install_script.sh.template
Labels: documentation, mergequeue-status: in_progress

#258 [gitlab] store test results artifacts by job id instead of by job name
  .gitlab-ci.yml
Labels: mergequeue-status: in_progress

#260 [gitlab] always upload test results
  .gitlab-ci.yml
Labels: mergequeue-status: rejected
