Repository DataDog/agent-linux-install-script, pull requests merged in 2024-10, with the labels that each got.

#281 chore: [BARX-576] Don't run test_agent6 jobs from datadog-agent pipelines
  .gitlab-ci.yml
Labels: mergequeue-status: in_progress

#282 (fleet) add network healthchecks to the script
  install_script.sh.template
Labels: mergequeue-status: in_progress

#284 1.35.2 post release
  CHANGELOG.rst
  install_script.sh.template
  install_script_op_worker1.sh
  install_script_op_worker2.sh
Labels: mergequeue-status: rejected

#285 (fleet) fix network telemetry
  install_script.sh.template
Labels: mergequeue-status: rejected

#289 add more tested networks, fix missing comma, add e2e to validate the trace telemetry
  install_script.sh.template
  test/e2e/install_installer_test.go
Labels: mergequeue-status: in_progress

#292 fix(test): Use specific version of centos7 image without usage of http://mirrorlist.centos.org/
  .gitlab-ci.yml
Labels: mergequeue-status: in_progress

#286 Transfer ownership to container-ecosystems
  .github/CODEOWNERS
Labels: mergequeue-status: error
